export default [
  {
    titleKey: "sender_ids",
    icon: "mdi-message-question-outline",
    name: "SenderIds.index",
    hasOneOf: [
      "sender_id::add",
      "sender_id::remove",
      "sender_id::retrieve",
      "sender_id::update",
    ],
  },
  {
    titleKey: "Packages",
    icon: "mdi-message-flash-outline",
    name: "Packages.index",
    hasOneOf: [
      "packages::add",
      "packages::remove",
      "packages::retrieve",
      "packages::update",
      "packages::view_group",
      "packages::set_group",
      "packages::revoke_group",
      "packages::view_features",
    ],
  },
  {
    titleKey: "sellers",
    icon: "mdi-account-tie-voice",
    name: "Sellers.index",
    hasOneOf: [
      "sellers::add",
      "sellers::remove",
      "sellers::retrieve",
      "sellers::update",
      "sellers::view_group",
      "sellers::set_group",
      "sellers::revoke_group",
      "sellers::view_features",
    ],
  },
  {
    titleKey: "Groups",
    icon: "mdi-tag-multiple-outline",
    name: "Groups.index",
    hasOneOf: [
      "groups::add",
      "groups::remove",
      "groups::retrieve",
      "groups::update",
      "groups::view_permissions",
      "groups::set_permissions",
    ],
  },

  {
    titleKey: "Supervisors",
    icon: "mdi-account-tie-outline",
    name: "Supervisors.index",
    hasOneOf: [
      "supervisors::add",
      "supervisors::remove",
      "supervisors::retrieve",
      "supervisors::update",
      "supervisors::view_role",
      "supervisors::set_role",
      "supervisors::revoke_role",
      "supervisors::view_permissions",
    ],
  },
  {
    titleKey: "Roles",
    icon: "mdi-tag-text-outline",
    name: "Roles.index",
    hasOneOf: [
      "roles::add",
      "roles::remove",
      "roles::retrieve",
      "roles::update",
      "roles::view_permissions",
      "roles::set_permissions",
    ],
  },
];
